# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QFrame(self.centralwidget)
        self.TitleBar.setMinimumSize(QtCore.QSize(0, 40))
        self.TitleBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.TitleBar.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.TitleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TitleBar.setObjectName("TitleBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TitleBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.TitleBar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(20, 0, 681, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: White")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.TitleBar)
        self.frame_2.setMinimumSize(QtCore.QSize(40, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.minimize = QtWidgets.QPushButton(self.frame_2)
        self.minimize.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.minimize.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.minimize.setFont(font)
        self.minimize.setStyleSheet("QPushButton{\n"
"font: 16pt \"ROG Fonts\";\n"
"color: White;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(57, 57, 57)\n"
"}")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.TitleBar)
        self.frame_3.setMinimumSize(QtCore.QSize(40, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.close = QtWidgets.QPushButton(self.frame_3)
        self.close.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.close.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton{\n"
"font: 16pt \"ROG Fonts\";\n"
"color: White;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(57, 57, 57)\n"
"}")
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.TitleBar)
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu = QtWidgets.QFrame(self.body)
        self.Menu.setMinimumSize(QtCore.QSize(50, 0))
        self.Menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Menu.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menu.setObjectName("Menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.Menu)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame)
        self.btn_page_1.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.btn_page_1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_page_1.setFont(font)
        self.btn_page_1.setStyleSheet("QPushButton{\n"
"font: 8pt \"ROG Fonts\";\n"
"color: White;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(57, 57, 57)\n"
"}")
        self.btn_page_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Project/icon/face-detection-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_1.setIcon(icon)
        self.btn_page_1.setIconSize(QtCore.QSize(30, 30))
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.Menu)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_5)
        self.btn_page_2.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.btn_page_2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_page_2.setFont(font)
        self.btn_page_2.setStyleSheet("QPushButton{\n"
"font: 8pt \"ROG Fonts\";\n"
"color: White;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(57, 57, 57)\n"
"}")
        self.btn_page_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Project/icon/database-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_2.setIcon(icon1)
        self.btn_page_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.Menu)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.Menu)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.btn_page_3 = QtWidgets.QPushButton(self.frame_7)
        self.btn_page_3.setGeometry(QtCore.QRect(0, 0, 50, 50))
        self.btn_page_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_page_3.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_page_3.setFont(font)
        self.btn_page_3.setStyleSheet("QPushButton{\n"
"font: 8pt \"ROG Fonts\";\n"
"color: White;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color: rgb(67, 67, 67);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"background-color: rgb(57, 57, 57)\n"
"}")
        self.btn_page_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Project/icon/information-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_3.setIcon(icon2)
        self.btn_page_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_page_3.setObjectName("btn_page_3")
        self.verticalLayout_2.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.Menu)
        self.Content = QtWidgets.QFrame(self.body)
        self.Content.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.Content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Detect = QtWidgets.QWidget()
        self.Detect.setObjectName("Detect")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Detect)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_8 = QtWidgets.QFrame(self.Detect)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setContentsMargins(20, 20, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.realbody = QtWidgets.QFrame(self.frame_8)
        self.realbody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.realbody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.realbody.setObjectName("realbody")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.realbody)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.realbody)
        self.frame_9.setMinimumSize(QtCore.QSize(640, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setMinimumSize(QtCore.QSize(640, 480))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.Screen = QtWidgets.QLabel(self.frame_13)
        self.Screen.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.Screen.setMinimumSize(QtCore.QSize(640, 480))
        self.Screen.setMaximumSize(QtCore.QSize(640, 480))
        self.Screen.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.Screen.setText("")
        self.Screen.setObjectName("Screen")
        self.verticalLayout_5.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_9)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_9)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 311, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_15)
        self.textBrowser_2.setGeometry(QtCore.QRect(350, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("color: White;")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_2.setLineWidth(0)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_5.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_9)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_5.addWidget(self.frame_16)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.realbody)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.realbody)
        self.frame_10.setMinimumSize(QtCore.QSize(260, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 120, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 221, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(20, 150, 221, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;")
        self.label_10.setObjectName("label_10")
        self.minimize_4 = QtWidgets.QPushButton(self.frame_10)
        self.minimize_4.setGeometry(QtCore.QRect(70, 250, 120, 40))
        self.minimize_4.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(10)
        self.minimize_4.setFont(font)
        self.minimize_4.setStyleSheet("QPushButton{\n"
"color: White;\n"
"background-color: rgb(47, 47, 47);\n"
"border-style: outset;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.minimize_4.setObjectName("minimize_4")
        self.minimize_5 = QtWidgets.QPushButton(self.frame_10)
        self.minimize_5.setGeometry(QtCore.QRect(50, 500, 160, 40))
        self.minimize_5.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(10)
        self.minimize_5.setFont(font)
        self.minimize_5.setStyleSheet("QPushButton{\n"
"color: White;\n"
"background-color: rgb(47, 47, 47);\n"
"border-style: outset;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.minimize_5.setObjectName("minimize_5")
        self.comboBox = QtWidgets.QComboBox(self.frame_10)
        self.comboBox.setGeometry(QtCore.QRect(20, 190, 221, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                 stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #D3D3D3, stop: 0.4 #D8D8D8,\n"
"                                stop: 0.5 #DDDDDD, stop: 1.0 #E1E1E1);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: lightgray;\n"
"    background-color: lightgray;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_10)
        self.textBrowser.setGeometry(QtCore.QRect(10, 300, 241, 41))
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("color: White;")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_12 = QtWidgets.QFrame(self.realbody)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3.addWidget(self.frame_12)
        self.gridLayout.addWidget(self.realbody, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.Detect)
        self.Datatable = QtWidgets.QWidget()
        self.Datatable.setObjectName("Datatable")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Datatable)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_17 = QtWidgets.QFrame(self.Datatable)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.Datatable)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_20 = QtWidgets.QFrame(self.frame_18)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_4.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_18)
        self.frame_21.setMinimumSize(QtCore.QSize(844, 0))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_21)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 781, 311))
        self.tableWidget.setMaximumSize(QtCore.QSize(781, 16777215))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"color: white;\n"
"background-color: rgb(57, 57, 57);\n"
"alternate-background-color: rgb(63, 63, 63);\n"
"selection-background-color: rgb(81, 81, 81);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(206, 206, 206);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(172, 172, 172);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(86, 86, 86);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(63, 63, 63);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(63, 63, 63);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(63, 63, 63);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(63, 63, 63);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(63, 63, 63);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(63, 63, 63);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(200)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label_9 = QtWidgets.QLabel(self.frame_21)
        self.label_9.setGeometry(QtCore.QRect(310, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: White")
        self.label_9.setObjectName("label_9")
        self.connectdatabase = QtWidgets.QPushButton(self.frame_21)
        self.connectdatabase.setGeometry(QtCore.QRect(340, 380, 160, 40))
        self.connectdatabase.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(10)
        self.connectdatabase.setFont(font)
        self.connectdatabase.setStyleSheet("QPushButton{\n"
"color: White;\n"
"background-color: rgb(47, 47, 47);\n"
"border-style: outset;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.connectdatabase.setObjectName("connectdatabase")
        self.databrow = QtWidgets.QTextBrowser(self.frame_21)
        self.databrow.setGeometry(QtCore.QRect(280, 420, 471, 61))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(12)
        self.databrow.setFont(font)
        self.databrow.setStyleSheet("color: white;")
        self.databrow.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.databrow.setObjectName("databrow")
        self.horizontalLayout_4.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_18)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_4.addWidget(self.frame_22)
        self.verticalLayout_7.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.Datatable)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_7.addWidget(self.frame_19)
        self.stackedWidget.addWidget(self.Datatable)
        self.Info = QtWidgets.QWidget()
        self.Info.setObjectName("Info")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Info)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_27 = QtWidgets.QFrame(self.Info)
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_6.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.Info)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_7.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_28)
        self.frame_31.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_31.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.label_4 = QtWidgets.QLabel(self.frame_31)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: White")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_31)
        self.label_5.setGeometry(QtCore.QRect(10, 440, 561, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: White")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_31)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 561, 201))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: White")
        self.label_7.setObjectName("label_7")
        self.cleardataall = QtWidgets.QPushButton(self.frame_31)
        self.cleardataall.setGeometry(QtCore.QRect(200, 370, 160, 40))
        self.cleardataall.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(10)
        self.cleardataall.setFont(font)
        self.cleardataall.setStyleSheet("QPushButton{\n"
"color: White;\n"
"background-color: rgb(47, 47, 47);\n"
"border-style: outset;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.cleardataall.setObjectName("cleardataall")
        self.label_8 = QtWidgets.QLabel(self.frame_31)
        self.label_8.setGeometry(QtCore.QRect(130, 410, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: White")
        self.label_8.setObjectName("label_8")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.frame_31)
        self.textBrowser_3.setGeometry(QtCore.QRect(0, 300, 591, 61))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(12)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("color: white;")
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.horizontalLayout_7.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_28)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_7.addWidget(self.frame_32)
        self.verticalLayout_6.addWidget(self.frame_28)
        self.frame_29 = QtWidgets.QFrame(self.Info)
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_6.addWidget(self.frame_29)
        self.stackedWidget.addWidget(self.Info)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.Content)
        self.verticalLayout.addWidget(self.body)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(48, 48, 48);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "63120028\'s Face Recognition"))
        self.minimize.setText(_translate("MainWindow", "_"))
        self.close.setText(_translate("MainWindow", "X"))
        self.label_6.setText(_translate("MainWindow", "CAMERA STATUS"))
        self.textBrowser_2.setPlaceholderText(_translate("MainWindow", "unknow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your ID number"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter your name"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "tier"))
        self.minimize_4.setText(_translate("MainWindow", "save"))
        self.minimize_5.setText(_translate("MainWindow", "SHOW ME"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Teacher"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Student"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Else"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TIER"))
        self.label_9.setText(_translate("MainWindow", "DATABASE"))
        self.connectdatabase.setText(_translate("MainWindow", "REFRESH"))
        self.label_4.setText(_translate("MainWindow", "information"))
        self.label_5.setText(_translate("MainWindow", "Contact me\n"
"E-mail : 63120028@kmitl.ac.th\n"
"Tel : Not gonna tell you"))
        self.label_7.setText(_translate("MainWindow", "Package include\n"
"\n"
" -PyQt5\n"
" -face_recognition\n"
" -openCV\n"
" -sqlite3\n"
" -pickle\n"
"\n"
" And a lot more\n"
"This is just information example"))
        self.cleardataall.setText(_translate("MainWindow", "Clear data"))
        self.label_8.setText(_translate("MainWindow", "P.S. There is no confirmation window."))
